import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import style from '../styles/Home.module.scss';
import classNames from 'classnames/bind';
import PageWrapper from '../components/PageWrapper/PageWrapper';

const cx = classNames.bind(style);

const Home: NextPage = () => {
  return (
    <PageWrapper>
      <Head>
        <title>Nova two</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={cx('title')}>Hello</h1>
    </PageWrapper>
  );
};

export default Home;
