import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import style from "../styles/Home.module.scss";
import classNames from "classnames/bind";
import PageWrapper from "../components/PageWrapper/PageWrapper";
import Hero from "../components/widgets/Hero";

const cx = classNames.bind(style);

const Home: NextPage = () => {
  return (
    <PageWrapper>
      <Head>
        <title>Nova two</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={cx("title")}>Nova 2</h1>
      <Hero />
      {/* <div className="" */}
    </PageWrapper>
  );
};

export default Home;
